apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Build"
metadata:
  name: "docker-ros-build"
spec:
  recipe: "Docker"
  architecture: "amd64"

  # gitRef: "master"
  # secret: "secret-guid"
  # contextDir: "talker/talker"
  rosDistro: "melodic"
  repository:
    url: "https://github.com/rapyuta-robotics/io_tutorials.git"
  buildMethod: "Source"

