apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Network"
metadata:
  name: "network-native-cloud"
  region: jp
  labels:
    app: test
spec:
  type: "native" # Required, Options: [routed, native]
  rosDistro: "melodic" # Required, Options: [kinetic, melodic, noetic]
  runtime: "cloud" # Required, Options: [cloud, device]
  resourceLimits:
    cpu: 0.1 # Unit: Core Options: [Multiple of 0.025, <= 8]
    memory: 512 # Unit: MB Options: [Multiple of 128, <= 32768]
