apiVersion: "apiextensions.rapyuta.io/v1"
kind: "Secret"
metadata:
  name: "secret-docker"
  labels:
    app: test
spec:
  type: Docker
  docker:
    username: user # Required
    password: password # Required
    email: user@example.net # Required
    registry: https://index.docker.io/v1/