---
apiVersion: api.rapyuta.io/v2
kind: UserGroup
metadata:
  name: usergroup_name
  labels:
    key: value
spec:
  description: This is a sample user group description
  members:
  - subject:
      kind: User
      name: qa.rapyuta+e2e@gmail.com
    roleNames: [ rio-group_admin ]
  - subject:
      kind: ServiceAccount
      name: sa-paramsync
    roleNames: [ group_viewer ]
  roles:
  - domain:
      kind: Project
      name: site-1
    roleName: project_admin
  - domain:
      kind: Project
      name: site-2
    roleName: project_viewer
